"""Initial migration

Revision ID: ee599928db06
Revises: 
Create Date: 2024-10-16 12:10:34.122311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee599928db06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raffle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prize_description', sa.Text(), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('ticket_price', sa.Float(), nullable=False),
    sa.Column('number_of_tickets', sa.Integer(), nullable=False),
    sa.Column('max_tickets_per_user', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMING_SOON', 'ACTIVE', 'SOLD_OUT', 'PAUSED', 'ENDED', 'CANCELLED', name='rafflestatus'), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('general_terms_link', sa.String(length=255), nullable=False),
    sa.Column('number_of_draws', sa.Integer(), nullable=False),
    sa.Column('prize_value', sa.Float(), nullable=False),
    sa.Column('prize_distribution_type', sa.Enum('FULL', 'SPLIT', name='prizedistributiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('raffle')
    # ### end Alembic commands ###
